loevgaard_sylius_optimize_images_admin_image_optimization_result:
    resource: |
        alias: loevgaard_sylius_optimize_images.image_optimization_result
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: loevgaard_sylius_optimize_images_admin_image_optimization_result
        vars:
            all:
                subheader: loevgaard_sylius_optimize_images.ui.view_image_optimization_results
            index:
                icon: 'tachometer alternate'
    type: sylius.resource