imports:
    - { resource: "@SetonoSyliusImageOptimizerPlugin/Resources/config/grids/setono_sylius_image_optimizer_admin_savings.yaml" }

framework:
    messenger:
        buses:
            setono_sylius_image_optimizer.command_bus: ~
            setono_sylius_image_optimizer.event_bus:
                default_middleware: allow_no_handlers
