framework:
    messenger:
        buses:
            setono_sylius_image_optimizer.command_bus: ~
            setono_sylius_image_optimizer.event_bus:
                default_middleware: allow_no_handlers
